-- Creates the SEPTA niche catalog tables and the two provenance columns on
-- septa_bids (see app/scrapers/septa/niche_models.py and models.py). On a fresh
-- database create_all makes these automatically and this file is not needed; run
-- it once against an existing database that predates niche-based scraping:
--
--   psql "$DATABASE_URL" -f server/migrations/2026-07-30_add_septa_niches.sql
--
-- The catalog rows themselves are NOT inserted here — they are seeded from
-- app/scrapers/septa/niches.py every time the API starts.
--
-- Idempotent — safe to run more than once.
CREATE TABLE IF NOT EXISTS septa_niches (
    key         VARCHAR(64) PRIMARY KEY,
    label       VARCHAR(255) NOT NULL,
    slug        VARCHAR(128),
    sort_order  INTEGER DEFAULT 0,
    is_active   BOOLEAN DEFAULT TRUE,
    updated_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS septa_niche_keywords (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    niche_key   VARCHAR(64) REFERENCES septa_niches(key) ON DELETE CASCADE,
    term        VARCHAR(255) NOT NULL,
    tier        VARCHAR(32),
    notes       TEXT,
    sort_order  INTEGER DEFAULT 0,
    CONSTRAINT uq_septa_niche_keyword UNIQUE (niche_key, term)
);

CREATE TABLE IF NOT EXISTS septa_niche_codes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    niche_key   VARCHAR(64) REFERENCES septa_niches(key) ON DELETE CASCADE,
    code        VARCHAR(64) NOT NULL,
    title       TEXT,
    notes       TEXT,
    sort_order  INTEGER DEFAULT 0,
    CONSTRAINT uq_septa_niche_code UNIQUE (niche_key, code)
);

CREATE INDEX IF NOT EXISTS ix_septa_niche_keywords_niche_key ON septa_niche_keywords (niche_key);
CREATE INDEX IF NOT EXISTS ix_septa_niche_codes_niche_key ON septa_niche_codes (niche_key);

-- Provenance on each scraped quote: the niche the run used, and the term(s)
-- that surfaced this requisition (comma-joined — a quote is often found by
-- several of a niche's keywords/codes).
ALTER TABLE septa_bids ADD COLUMN IF NOT EXISTS niche VARCHAR(64);
ALTER TABLE septa_bids ADD COLUMN IF NOT EXISTS matched_terms TEXT;

CREATE INDEX IF NOT EXISTS ix_septa_bids_niche ON septa_bids (niche);
