-- Creates the SAM, Unison, NAICS, and eval-config tables (see the respective
-- app/scrapers/<portal>/models.py). On a fresh database create_all makes these
-- automatically and this file is not needed; run it once against an existing
-- database that predates these scrapers:
--
--   psql "$DATABASE_URL" -f server/migrations/2026-07-22_add_sam_unison_naics_evalconfig_tables.sql
--
-- Idempotent — safe to run more than once.

-- ── Evaluator config (kill words / allowed / excluded service lists) ─────────
CREATE TABLE IF NOT EXISTS eval_config (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category  VARCHAR(30),
    value     VARCHAR(200)
);
CREATE INDEX IF NOT EXISTS ix_eval_config_category ON eval_config (category);
CREATE INDEX IF NOT EXISTS ix_eval_config_value ON eval_config (value);

-- ── SAM.gov ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sam_runs (
    run_id                VARCHAR(32) PRIMARY KEY,
    status                VARCHAR(32),
    started_at            TIMESTAMPTZ,
    finished_at           TIMESTAMPTZ,
    search                TEXT,
    bids_found            INTEGER DEFAULT 0,
    documents_downloaded  INTEGER DEFAULT 0,
    folder                TEXT,
    excel_path            TEXT,
    ingested_at           TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sam_bids (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id            VARCHAR(32) REFERENCES sam_runs(run_id) ON DELETE CASCADE,
    scraped_at        TIMESTAMPTZ DEFAULT now(),
    notice_id         VARCHAR(255),
    title             TEXT,
    department        TEXT,
    subtier           TEXT,
    office            TEXT,
    description       TEXT,
    updated_date      VARCHAR(64),
    bid_repeat_count  INTEGER DEFAULT 0,
    naics_code        VARCHAR(32),
    naics_title       TEXT,
    date_offers_due   VARCHAR(64),
    published_date    VARCHAR(64),
    decision          VARCHAR(20),
    reason            TEXT,
    raw_data          JSONB DEFAULT '{}'::jsonb,
    CONSTRAINT uq_sam_run_notice UNIQUE (run_id, notice_id)
);
CREATE INDEX IF NOT EXISTS ix_sam_bids_run_id ON sam_bids (run_id);
CREATE INDEX IF NOT EXISTS ix_sam_bids_notice_id ON sam_bids (notice_id);

-- ── Unison Marketplace ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS unison_runs (
    run_id                VARCHAR(32) PRIMARY KEY,
    status                VARCHAR(32),
    started_at            TIMESTAMPTZ,
    finished_at           TIMESTAMPTZ,
    search                TEXT,
    bids_found            INTEGER DEFAULT 0,
    documents_downloaded  INTEGER DEFAULT 0,
    folder                TEXT,
    excel_path            TEXT,
    ingested_at           TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS unison_requests (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id             VARCHAR(32) REFERENCES unison_runs(run_id) ON DELETE CASCADE,
    scraped_at         TIMESTAMPTZ DEFAULT now(),
    buyer_number       VARCHAR(255),
    buyer_description  TEXT,
    buyer              TEXT,
    end_date           VARCHAR(255),
    raw_data           JSONB DEFAULT '{}'::jsonb,
    CONSTRAINT uq_unison_run_buyer UNIQUE (run_id, buyer_number)
);
CREATE INDEX IF NOT EXISTS ix_unison_requests_run_id ON unison_requests (run_id);
CREATE INDEX IF NOT EXISTS ix_unison_requests_buyer_number ON unison_requests (buyer_number);

-- ── NAICS reference codes ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS naics_codes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(10) UNIQUE,
    title       TEXT,
    scraped_at  TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_naics_codes_code ON naics_codes (code);
