-- Creates the North Dakota (ND Buys / Ivalua) tables (see
-- app/scrapers/northdakota/models.py). On a fresh database create_all makes
-- these automatically and this file is not needed; run it once against an
-- existing database that predates the North Dakota scraper:
--
--   psql "$DATABASE_URL" -f server/migrations/2026-07-18_add_northdakota_tables.sql
--
-- Idempotent — safe to run more than once.
CREATE TABLE IF NOT EXISTS northdakota_runs (
    run_id                VARCHAR(32) PRIMARY KEY,
    status                VARCHAR(32),
    started_at            TIMESTAMPTZ,
    finished_at           TIMESTAMPTZ,
    search                TEXT,
    bids_found            INTEGER DEFAULT 0,
    documents_downloaded  INTEGER DEFAULT 0,
    folder                TEXT,
    excel_path            TEXT,
    ingested_at           TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS northdakota_bids (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id           VARCHAR(32) REFERENCES northdakota_runs(run_id) ON DELETE CASCADE,
    scraped_at       TIMESTAMPTZ DEFAULT now(),
    rfp_id           VARCHAR(64),
    title            TEXT,
    pub_begin_date   VARCHAR(64),
    pub_end_date     VARCHAR(64),
    begin_date       VARCHAR(64),
    close_date       VARCHAR(64),
    commodity        TEXT,
    remaining_time   VARCHAR(128),
    status           VARCHAR(64),
    detail_url       TEXT,
    matched_keyword  TEXT,
    raw_data         JSONB DEFAULT '{}'::jsonb,
    CONSTRAINT uq_northdakota_run_rfp UNIQUE (run_id, rfp_id)
);

CREATE INDEX IF NOT EXISTS ix_northdakota_bids_run_id ON northdakota_bids (run_id);
CREATE INDEX IF NOT EXISTS ix_northdakota_bids_rfp_id ON northdakota_bids (rfp_id);
