-- Adds the SEPTA Open Bids table (see app/scrapers/septa/models.py).
--
-- A SEPTA run now reads both of the portal's modules: Open Quotes, which keeps
-- landing in septa_bids, and the Bid module, which lands here. They are kept
-- apart because the key column means something different in each — a
-- requisition number there, a bid number here — so a shared table would have a
-- dedup key that is only unique within half its rows.
--
-- On a fresh database create_all makes this automatically and this file is not
-- needed; run it once against a database that predates the Open Bids pass:
--
--   psql "$DATABASE_URL" -f server/migrations/2026-08-05_add_septa_open_bids.sql
--
-- Idempotent — safe to run more than once.
CREATE TABLE IF NOT EXISTS septa_open_bids (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id      VARCHAR(32) REFERENCES septa_runs(run_id) ON DELETE CASCADE,
    scraped_at  TIMESTAMPTZ DEFAULT now(),
    bid_number  VARCHAR(255),
    title       TEXT,
    open_date   VARCHAR(64),
    close_date  VARCHAR(64),
    raw_data    JSONB DEFAULT '{}'::jsonb,
    CONSTRAINT uq_septa_run_bid_number UNIQUE (run_id, bid_number)
);

CREATE INDEX IF NOT EXISTS ix_septa_open_bids_run_id ON septa_open_bids (run_id);
CREATE INDEX IF NOT EXISTS ix_septa_open_bids_bid_number ON septa_open_bids (bid_number);
