-- Creates the SEPTA (vendor procurement portal) tables (see
-- app/scrapers/septa/models.py). On a fresh database create_all makes these
-- automatically and this file is not needed; run it once against an existing
-- database that predates the SEPTA scraper:
--
--   psql "$DATABASE_URL" -f server/migrations/2026-07-20_add_septa_tables.sql
--
-- Idempotent — safe to run more than once.
CREATE TABLE IF NOT EXISTS septa_runs (
    run_id                VARCHAR(32) PRIMARY KEY,
    status                VARCHAR(32),
    started_at            TIMESTAMPTZ,
    finished_at           TIMESTAMPTZ,
    search                TEXT,
    bids_found            INTEGER DEFAULT 0,
    documents_downloaded  INTEGER DEFAULT 0,
    folder                TEXT,
    excel_path            TEXT,
    ingested_at           TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS septa_bids (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id              VARCHAR(32) REFERENCES septa_runs(run_id) ON DELETE CASCADE,
    scraped_at          TIMESTAMPTZ DEFAULT now(),
    requisition_number  VARCHAR(255),
    summary             TEXT,
    open_date           VARCHAR(64),
    close_date          VARCHAR(64),
    raw_data            JSONB DEFAULT '{}'::jsonb,
    CONSTRAINT uq_septa_run_requisition UNIQUE (run_id, requisition_number)
);

CREATE INDEX IF NOT EXISTS ix_septa_bids_run_id ON septa_bids (run_id);
CREATE INDEX IF NOT EXISTS ix_septa_bids_requisition_number ON septa_bids (requisition_number);
