-- Creates the BidNet Direct niche catalog tables (see
-- app/scrapers/bidnet/niche_models.py). On a fresh database create_all makes
-- these automatically and this file is not needed; run it once against an
-- existing database that predates niche-based scraping:
--
--   psql "$DATABASE_URL" -f server/migrations/2026-07-31_add_bidnet_niches.sql
--
-- The catalog rows themselves are NOT inserted here — they are seeded from
-- app/scrapers/bidnet/niches.py every time the API starts.
--
-- Idempotent — safe to run more than once.
CREATE TABLE IF NOT EXISTS bidnet_niches (
    key         VARCHAR(64) PRIMARY KEY,
    label       VARCHAR(255) NOT NULL,
    slug        VARCHAR(128),
    notes       TEXT,
    sort_order  INTEGER DEFAULT 0,
    is_active   BOOLEAN DEFAULT TRUE,
    updated_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS bidnet_niche_keywords (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    niche_key   VARCHAR(64) REFERENCES bidnet_niches(key) ON DELETE CASCADE,
    term        VARCHAR(255) NOT NULL,
    notes       TEXT,
    sort_order  INTEGER DEFAULT 0,
    CONSTRAINT uq_bidnet_niche_keyword UNIQUE (niche_key, term)
);

CREATE INDEX IF NOT EXISTS ix_bidnet_niche_keywords_niche_key
    ON bidnet_niche_keywords (niche_key);

-- Which niche produced a bid, so the master spreadsheet and later queries can
-- say where a solicitation came from.
ALTER TABLE bidnet_bids ADD COLUMN IF NOT EXISTS niche VARCHAR(64);
